name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
          npm list

      # Modified test step with more verbose output
      - name: Run Tests
        run: |
          echo "Running tests with Node ${{ matrix.node-version }}"
          npm test -- --verbose --detectOpenHandles --forceExit > test-output.txt 2>&1
        env:
          CI: true
          NODE_ENV: test

      - name: Build
        run: npm run build
        if: success()

      - name: Lint
        run: npm run lint
        if: success()

      # Upload test output as artifact
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            coverage/
            test-output.txt
          retention-days: 5

      # Display test output even if tests fail
      - name: Display Test Output
        if: always()
        run: cat test-output.txt
